// Generated by CoffeeScript 1.3.3
(function() {
  var app, express, express_validator, flash, http, path, routes;

  express_validator = require('express-validator');

  express = require('express');

  routes = require('./routes');

  http = require('http');

  path = require('path');

  flash = require('connect-flash');

  require('express-namespace');

  app = express();

  app.configure(function() {
    app.set('port', process.env.PORT || 8080);
    app.set('views', __dirname + '/views');
    app.set('view engine', 'jade');
    app.use(express.favicon());
    app.use(express.logger('dev'));
    app.use(express.bodyParser());
    app.use(express_validator);
    app.use(express.methodOverride());
    app.use(express.cookieParser('0nl1n3'));
    app.use(express.session({
      cookie: {
        maxAge: 60000
      }
    }));
    app.use(flash());
    app.use(app.router);
    app.use(require('stylus').middleware(__dirname + '/public'));
    return app.use(express["static"](path.join(__dirname, 'public')));
  });

  app.configure('development', function() {
    return app.use(express.errorHandler());
  });

  require('./routes/general')(app);

  require('./apps/admin/routes')(app);

  app.get('/', routes.index);

  http.createServer(app).listen(app.get('port'), function() {
    return console.log("Express server listening on port " + app.get('port'));
  });

}).call(this);
