// Generated by CoffeeScript 1.3.3
(function() {
  var GoogleMovies, Movie, Showtimes;

  Showtimes = require("./showtimes");

  Movie = require('./movie');

  GoogleMovies = (function() {

    function GoogleMovies() {}

    GoogleMovies.prototype.run = function($) {
      var movies;
      movies = [];
      $(".showtimes .movie").each(function() {
        var name, showtimes;
        name = $('.name', this).text();
        showtimes = $.map($('.times', this).text().split('&nbsp'), function(val) {
          return val.replace(/[^a-zA-Z0-9:\-]/g, '');
        });
        return movies.push(new Movie(name, showtimes));
      });
      return movies;
    };

    return GoogleMovies;

  })();

  module.exports = GoogleMovies;

}).call(this);
