// Generated by CoffeeScript 1.3.3
(function() {
  var GoogleMovies, Showtimes, jsdom;

  jsdom = require("jsdom");

  Showtimes = (function() {

    function Showtimes(url, scraper) {
      var _this = this;
      this.url = url;
      this.scraper = scraper;
      jsdom.env({
        html: this.url,
        scripts: ["http://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"],
        done: function(errors, window) {
          var $;
          $ = window.$;
          return _this.scraper.run($);
        }
      });
    }

    return Showtimes;

  })();

  GoogleMovies = (function() {

    function GoogleMovies() {}

    GoogleMovies.prototype.run = function($) {
      return $(".showtimes .movie").each(function() {
        var movie, showtimes;
        movie = $('.name', this).text();
        showtimes = $.map($('.times', this).text().split('&nbsp'), function(val, i) {
          return console.log(val, i);
        });
        return console.log(" -", showtimes);
      });
    };

    return GoogleMovies;

  })();

  new Showtimes("http://www.google.com.br/movies?near=porto+alegre&tid=1f76f971434a044", new GoogleMovies);

}).call(this);
