// Generated by CoffeeScript 1.3.3
(function() {
  var Movie, MovieParser, jsdom;

  Movie = require('./movie');

  jsdom = require("jsdom");

  MovieParser = (function() {
    var _movies;

    _movies = [];

    function MovieParser(url) {
      this.scrape(url);
    }

    MovieParser.prototype.scrape = function(url) {
      var _this = this;
      return jsdom.env({
        html: url,
        scripts: ["http://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"],
        done: function(errors, window) {
          return _this.parse(window.$);
        }
      });
    };

    MovieParser.prototype.addMovie = function(name, showtimes) {
      return _movies.push(new Movie(name, showtimes));
    };

    MovieParser.prototype.print = function() {
      return console.log(_movies);
    };

    MovieParser.example = function() {};

    MovieParser.prototype.parse = function($) {};

    return MovieParser;

  })();

  module.exports = MovieParser;

}).call(this);
