// Generated by CoffeeScript 1.3.3
(function() {
  var Parser, jsdom;

  jsdom = require("jsdom");

  Parser = (function() {

    function Parser(url, parser) {
      var _this = this;
      this.url = url;
      this.parser = parser;
      jsdom.env({
        html: this.url,
        scripts: ["http://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"],
        done: function(errors, window) {
          var $;
          $ = window.$;
          return _this.scraper.run($);
        }
      });
    }

    return Parser;

  })();

  module.exports = Parser;

}).call(this);
