// Generated by CoffeeScript 1.3.3
(function() {

  global.sinon = require("sinon");

  global.chai = require("chai");

  global.should = require("chai").should();

  global.expect = require("chai").expect;

}).call(this);
