// Generated by CoffeeScript 1.3.3
(function() {
  var Movie;

  Movie = require('../movie');

  describe('Movie', function() {
    return it('should have at least a name and showtimes', function() {
      var movie;
      movie = new Movie('Rocky');
      movie.setShowtime('10:30');
      movie.setShowtime('18:40');
      expect(movie.name).to.equal('Rocky');
      return expect(movie.showtimes.length).to.equal(2);
    });
  });

}).call(this);
