// Generated by CoffeeScript 1.3.3
(function() {
  var Movie;

  Movie = require('../movie');

  describe('Movie', function() {
    it('should have at least a name and showtimes', function() {
      var movie;
      movie = new Movie('Rocky');
      movie.setShowtime('10:30');
      movie.setShowtime('18:40');
      expect(movie.name).to.equal('Rocky');
      return expect(movie.showtimes.length).to.equal(2);
    });
    it('should have name sanitized', function() {
      expect(new Movie('Rocky legendado').name).to.equal('Rocky');
      expect(new Movie('Rocky - legendado').name).to.equal('Rocky');
      expect(new Movie('Rocky -Legendado').name).to.equal('Rocky');
      expect(new Movie('Rocky -dublado').name).to.equal('Rocky');
      expect(new Movie('Rocky - dublado').name).to.equal('Rocky');
      expect(new Movie('Rocky dublado ').name).to.equal('Rocky');
      expect(new Movie('Rocky DUB.').name).to.equal('Rocky');
      expect(new Movie('Rocky - DUB.').name).to.equal('Rocky');
      expect(new Movie('Rocky -LEG').name).to.equal('Rocky');
      expect(new Movie('Rocky - LEG').name).to.equal('Rocky');
      expect(new Movie('Rocky / DUB.').name).to.equal('Rocky');
      expect(new Movie('Rocky / DUB').name).to.equal('Rocky');
      return expect(new Movie('Rocky /DUB').name).to.equal('Rocky');
    });
    return it('should extract the subtitle', function() {
      expect(new Movie('Rocky legendado').subtitle).to.equal('legendado');
      expect(new Movie('Rocky - legendado').subtitle).to.equal('legendado');
      expect(new Movie('Rocky -Legendado').subtitle).to.equal('legendado');
      expect(new Movie('Rocky -dublado').subtitle).to.equal('dublado');
      expect(new Movie('Rocky - dublado').subtitle).to.equal('dublado');
      expect(new Movie('Rocky dublado ').subtitle).to.equal('dublado');
      expect(new Movie('Rocky DUB.').subtitle).to.equal('dublado');
      expect(new Movie('Rocky - DUB.').subtitle).to.equal('dublado');
      expect(new Movie('Rocky / DUB.').subtitle).to.equal('dublado');
      expect(new Movie('Rocky / DUB').subtitle).to.equal('dublado');
      expect(new Movie('Rocky /DUB').subtitle).to.equal('dublado');
      expect(new Movie('Rocky -LEG').subtitle).to.equal('legendado');
      return expect(new Movie('Rocky - LEG').subtitle).to.equal('legendado');
    });
  });

}).call(this);
