// Generated by CoffeeScript 1.3.3
(function() {
  var Movie;

  Movie = (function() {

    function Movie(name, showtimes, subtitle, _3d) {
      this.name = name;
      this.showtimes = showtimes != null ? showtimes : [];
      this.subtitle = subtitle != null ? subtitle : 'legendado';
      this._3d = _3d != null ? _3d : false;
    }

    Movie.prototype.setShowtime = function(showtime) {
      return this.showtimes.push(showtime);
    };

    return Movie;

  })();

  module.exports = Movie;

}).call(this);
