// Generated by CoffeeScript 1.3.3
(function() {
  var Movie;

  Movie = (function() {

    function Movie(name, showtimes) {
      this.name = name;
      this.showtimes = showtimes != null ? showtimes : [];
    }

    Movie.prototype.setShowtime = function(showtime) {
      return this.showtimes.push(showtime);
    };

    return Movie;

  })();

  module.exports = Movie;

}).call(this);
