// Generated by CoffeeScript 1.3.3
(function() {
  var Movie, MovieParser, jsdom, request;

  Movie = require('./movie');

  jsdom = require('jsdom');

  request = require('request');

  MovieParser = (function() {

    function MovieParser(url, cb) {
      this._movies = [];
      this.scrape(url, cb);
    }

    MovieParser.prototype.scrape = function(url, cb) {
      var _this = this;
      return request({
        uri: url,
        encoding: 'binary'
      }, function(error, response, body) {
        return jsdom.env({
          html: body,
          scripts: ["http://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"],
          done: function(errors, window) {
            _this.parse(window.$);
            return cb(_this._movies);
          }
        });
      });
    };

    MovieParser.prototype.addMovie = function(name, showtimes) {
      return this._movies.push(new Movie(name, showtimes));
    };

    MovieParser.example = function() {};

    MovieParser.prototype.parse = function($) {};

    return MovieParser;

  })();

  module.exports = MovieParser;

}).call(this);
