// Generated by CoffeeScript 1.3.3
(function() {
  var Movie, MovieParser, jsdom, request;

  Movie = require('./movie');

  jsdom = require('jsdom');

  request = require('request');

  MovieParser = (function() {

    function MovieParser(url, cb) {
      this._movies = [];
      this.scrape(url, cb);
    }

    MovieParser.prototype.scrape = function(url, cb) {
      var start,
        _this = this;
      start = new Date().getTime();
      return request({
        uri: url,
        encoding: 'binary'
      }, function(error, response, body) {
        return jsdom.env({
          html: body,
          scripts: ["http://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"],
          done: function(errors, window) {
            var benchmark;
            _this.parse(window.$);
            benchmark = (new Date().getTime()) - start;
            return cb(_this._movies, benchmark);
          }
        });
      });
    };

    MovieParser.prototype.addMovie = function(name, showtimes) {
      return this._movies.push(new Movie(name, showtimes));
    };

    MovieParser.example_url = function() {};

    MovieParser.example = function() {
      var parser, url;
      parser = this.name;
      url = this.example_url();
      return new this(url, function(movies, benchmark) {
        console.log(movies);
        return console.log("Execution time: " + benchmark + "ms");
      });
    };

    MovieParser.prototype.parse = function($) {};

    return MovieParser;

  })();

  module.exports = MovieParser;

}).call(this);
