// Generated by CoffeeScript 1.3.3
(function() {
  var program;

  program = require('commander');

  program.command('*').action(function(parser) {
    parser = require("./" + parser);
    return parser.example();
  });

  // TODO loop through all parsers to print on examples
  program.on('--help', function() {
    console.log('  Examples:');
    console.log('');
    console.log('    $ print_showtimes google');
    return console.log('');
  });

  program.parse(process.argv);

  if (program.args.length === 0) {
    program.help();
  }

}).call(this);
