// Generated by CoffeeScript 1.3.3
(function() {
  var Showtimes, jsdom;

  jsdom = require("jsdom");

  Showtimes = (function() {

    function Showtimes(url, parser) {
      var _this = this;
      this.url = url;
      this.parser = parser;
      jsdom.env({
        html: this.url,
        scripts: ["http://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"],
        done: function(errors, window) {
          var $;
          $ = window.$;
          return _this.parser.run($);
        }
      });
    }

    return Showtimes;

  })();

  module.exports = Showtimes;

}).call(this);
